// Generated by Wrangler on Fri Jun 07 2024 01:39:37 GMT+1200 (New Zealand Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_D1_DATABASE_ID: string;
  CLOUDFLARE_TOKEN: string;
  DB: D1Database;
}
