# Your wrangler.toml file should look something like this:

name = "t3-cloudflare"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# If you are only using Pages + D1, you only need the below in your wrangler.toml to interact with D1 locally.
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "test-t3"
database_id = "6a9dfc39-72e9-4230-a360-8f489ce64864"
preview_database_id = "DB" # Required for Pages local development
